nohup: ignoring input
11/29/2022 08:43:17 PM [INFO]: Starting iteration pipeline...
11/29/2022 08:43:21 PM [INFO]: Preparing model for multi-process MCTS...
11/29/2022 08:43:21 PM [INFO]: Initialized model.
11/29/2022 08:43:21 PM [INFO]: Required number of processes exceed number of CPUs! Setting MCTS_num_processes to 4
11/29/2022 08:43:21 PM [INFO]: Spawning 4 processes...
11/29/2022 08:43:24 PM [INFO]: [CPU: 0]: Starting MCTS self-play...
  0%|          | 0/120 [00:00<?, ?it/s]11/29/2022 08:43:24 PM [INFO]: [CPU: 0]: Game 0
  0%|          | 0/120 [00:00<?, ?it/s]
Process Process-1:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/MCTS_c4.py", line 184, in MCTS_self_play
    root = UCT_search(current_board, 777, connectnet, t)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/MCTS_c4.py", line 141, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/alpha_net_c4.py", line 94, in forward
    s = self.conv(s)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/alpha_net_c4.py", line 34, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _thnn_conv2d_forward
11/29/2022 08:43:28 PM [INFO]: [CPU: 1]: Starting MCTS self-play...
  0%|          | 0/120 [00:00<?, ?it/s]11/29/2022 08:43:28 PM [INFO]: [CPU: 1]: Game 0
  0%|          | 0/120 [00:00<?, ?it/s]
Process Process-2:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/MCTS_c4.py", line 184, in MCTS_self_play
    root = UCT_search(current_board, 777, connectnet, t)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/MCTS_c4.py", line 141, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/alpha_net_c4.py", line 94, in forward
    s = self.conv(s)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/alpha_net_c4.py", line 34, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _thnn_conv2d_forward
11/29/2022 08:43:32 PM [INFO]: [CPU: 2]: Starting MCTS self-play...
  0%|          | 0/120 [00:00<?, ?it/s]11/29/2022 08:43:32 PM [INFO]: [CPU: 2]: Game 0
  0%|          | 0/120 [00:00<?, ?it/s]
Process Process-3:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/MCTS_c4.py", line 184, in MCTS_self_play
    root = UCT_search(current_board, 777, connectnet, t)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/MCTS_c4.py", line 141, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/alpha_net_c4.py", line 94, in forward
    s = self.conv(s)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/alpha_net_c4.py", line 34, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _thnn_conv2d_forward
11/29/2022 08:43:35 PM [INFO]: [CPU: 3]: Starting MCTS self-play...
  0%|          | 0/120 [00:00<?, ?it/s]11/29/2022 08:43:35 PM [INFO]: [CPU: 3]: Game 0
  0%|          | 0/120 [00:00<?, ?it/s]
Process Process-4:
Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/root/anaconda3/envs/pytorch/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/MCTS_c4.py", line 184, in MCTS_self_play
    root = UCT_search(current_board, 777, connectnet, t)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/MCTS_c4.py", line 141, in UCT_search
    child_priors, value_estimate = net(encoded_s)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/alpha_net_c4.py", line 94, in forward
    s = self.conv(s)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/alpha_net_c4.py", line 34, in forward
    s = F.relu(self.bn1(self.conv1(s)))
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/root/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Expected object of device type cuda but got device type cpu for argument #1 'self' in call to _thnn_conv2d_forward
11/29/2022 08:43:36 PM [INFO]: Finished multi-process MCTS!
11/29/2022 08:43:36 PM [INFO]: Loading training data...
11/29/2022 08:43:36 PM [INFO]: Loaded data from ../../datasets/iter_0/.
11/29/2022 08:43:36 PM [INFO]: Loaded checkpoint model ../../model_data/cc4_current_net__iter0.pth.tar.
Traceback (most recent call last):
  File "main_pipeline.py", line 39, in <module>
    train_connectNet(args, iteration=i, new_optim_state=True)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/train_c4.py", line 161, in train_connectNet
    train(net, datasets, optimizer, scheduler, start_epoch, 0, args, iteration)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/train_c4.py", line 70, in train
    train_set = board_data(dataset)
  File "/home/hhhhzl/game-engine-end/strategy/AlphaZero_connect4/alpha_net_c4.py", line 15, in __init__
    self.X = dataset[:, 0]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
